### ISSUE TITLE
Timepicker/Datepicker - Able to Type inside input to Set them

### ISSUE THREAD

**Issue by thinkClearNarinder** [rnwonder/solid-date-picker#26]
**Is your feature request related to a problem? Please describe.**

In the course of developing my ERP software, I discovered that a majority of users prefer utilizing the keyboard extensively. Hence, I believe integrating a datepicker and timepicker with keyboard accessibility would greatly enhance usability across various applications. 
Currently, I've implemented a standard input type="time" solution to address this need. However, the addition of this feature in future updates would be highly beneficial.

**Comment by rnwonder** [comment]
Interesting suggestion. How do you imagine it would work though in relation to how the date picker works currently?

I mean currently when you click on the input it opens the date picker. What should happen next. Say I type 2007, should the year change to 2007 or should it change the day to 20 and month to 07? 

I believe you should have an idea what I am asking by now. Basically just describe in details the idea user experience with this feature implemented and how the date picker will respond to it.

For the time picker you can do the same, but I can't promise I would be updating that anytime soon as its in beta. I don't have the time for a big update currently but if it seems simple enough I could do it nonetheless.

**Comment by rnwonder** [comment]
For better clarity... 
- Say I type 2 what happens to the input field and the date picker? Keep in mind the value display on the default input is formatted (for example May 4, 2024). So if a user input 2, what happens to the input value. Also how will it affect the date picker? Assuming the date picker is currently on the month of May and year is 2024 and the selected date is 4th.
- Say I type 23072024 what happens? 
- What happens if I then proceed to type 2 after this?

I think using a separate input which allows user's input and an icon by the side which opens the picker when clicked seems like a simpler approach. Which is probably similar to what you did with the standard input type="time". 

Making it a default property of the picker comes with a lot of intricacies by way of how existing features will respond to it. But if you or anyone else can come up with good UX that accounts for these then we can implement it.

**Comment by thinkClearNarinder** [comment]
@rnwonder 
Certainly, we can implement a solution where users can input dates in the format DD/MM/YYYY when they focus on the input field. Here's how we can structure it:

Allow users to input dates in the format DD/MM/YYYY directly into the input field when it is in focus.

After the user has entered all values, display the formatted date for better readability, such as "24 March 2024" or "March 24, 2024".

Implement validation for incomplete date entries. For instance, if a user enters "22/12/----", upon blur, indicate to the user that it is an invalid date. This feedback can be provided through helper text or within the input field itself.

This approach enhances user experience by providing a familiar date entry format and ensuring validation for accurate data input.

**Comment by rnwonder** [comment]
I think I understand what you are saying but it doesn't address my concern as to how it will affect the current implementation of the picker. Except you mean the picker should now come with an icon and input. Meaning the date picker only opens when the icon is clicked.

If thats what you mean, I feel its better implemented by the developer as they deem fit. The picker already gives you the framework to achieve this. I feel keeping the input side of things as simple as possible is best. If you need the added complexity you can replace the default input component with yours and setup this feature on your end. Which hopefully the picker allows you to do currently.

You will notice the default input is very rudimentary. That was intentional to keep things simple. Too much complexity makes the functionality of the picker difficult to grasp. 

Also this update will introduce a significant UI change which will affect websites currently using the default input. 

I rather a solution that keeps the current default UI look but enhances the UX. Its why I ask you explain how it should work in relation with the current default implementation. Stating how it affects not only the input but the picker as well.
